StudentCode-in/StudentCode-in.github.io

project.html
* Hardware:
* Toolchain:
* SDK:
=> Added Slack channel and projects

project.html
* Hardware:
* Toolchain:
* SDK:
=> Added projects

project.html
Updated  tech stack under  under my project in project.html file.
* Hardware:
* Toolchain:
* SDK:
=> Updated Tech Stack in my project

project.html
* Hardware:
* Toolchain:
* SDK:
=> Error resolved

project.html
* Hardware:
* Toolchain:
* SDK:
=> Added correct GitHub links to projects

project.html
* Hardware:
* Toolchain:
* SDK:
=> Added Mentors to projects

README.md
email links were not written properly in readme file.
Fixes #5 
I corrected mail links as well as twitter page link
=> email links showing correctly

index.html
* Hardware:
* Toolchain:
* SDK:
=> Added youtube link

index.html
* Hardware:
* Toolchain:
* SDK:
=> Grammer check

index.html
* Hardware:
* Toolchain:
* SDK:
=> Telegram Channel link added

assets/css/style.css, index.html
* Hardware:
* Toolchain:
* SDK:
=> Added sponsors

index.html
* Hardware:
* Toolchain:
* SDK:
=> added patrons

assets/css/style.css, index.html, project.html
* Hardware:
* Toolchain:
* SDK:
=> Patrons added

README.md
Here I fix few typos in the README.md.
=> README typo fixed

project.html, team.html
Updated Email Space in all Pages
=> Updated Email Space

assets/css/style.css, index.html, package-lock.json
Changed css of sponsors area to be more mobile friendly using flex-box and made it a tad more appealing to eyes
Fixes #49 
- [ ✓ ] Bug fix (non-breaking change which fixes an issue)
- [ X ] New feature (non-breaking change which adds functionality)
- [ X ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ X ] This change requires a documentation update
- [ X ] Test A
- [ X ] Test B
* Hardware:
* Toolchain:
* SDK:
- [ ✓ ] My code follows the style guidelines of this project
- [ ✓ ] I …
=> [DESIGN] Improved sponsors section

assets/js/main.js, project.html
Added a search bar on the projects page for users to filter the projects by keywords.
Fixes #50 
=> project searchbar

assets/css/style.css, assets/css/style1.css, assets/css/style2.css
Custom scrollbar styling with colors matching website
Fixes # (https://github.com/StudentCode-in/StudentCode-in.github.io/issues/57)
=> Custom scrollbar

assets/css/style1.css, assets/js/main.js, project.html
Improved the card popup on Project page as you asked. Now popup opens by clicking anywhere on card except the name of the project
Fixes # (65)
* Hardware:
* Toolchain:
* SDK:
=> Card popup improved in Project page

assets/js/main.js
I added a click event in the parent element div, with a check, if true closes the popup
Fixes #68 
I tested it by clicking on all popups to see if everyone was closing
* Hardware:
* Toolchain:
* SDK:
=> Fixed close popup when click outside

assets/js/main.js
I added same filtering logic like searching to check to perform tech stack related searching. 
Fixes #61
I tested with happy paths and edge cases 
* Hardware:
* Toolchain:
* SDK:
=> Search by clicking any tech stack #61

assets/css/style3.css, index.html, webinar.html
Created the webinar page by using given resource files. 
Fixes #52 
* Hardware:
* Toolchain:
* SDK:
=> Created the Webinar Page

assets/css/style.css, index.html
I have added a popup for registration closed. I have used a bootstrap modal for this.
Fixes #83 popup required.
=> Add popup for Registration closed

assets/js/main.js
Fixes #79 
Unused code
No test needed
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] My changes generate no new warnings
=> Remove unused js

assets/css/style2.css, index.html, team.html
I added lazy loading to image of team.html (`loading="lazy"`) on image and also Specifying a `width `and `height `for all your team images as suggested by **Google**. I added css class (`.img__color-palette`) for default images background color on style2.css. 
*Note : Automatically format of index.html and team.html files because I am using VS CODE.
I added below Screenshot of Before and After of team.html loading images Easily understanad what I did.
=> add lazy loading for images and add css class for deafult background color for images

assets/css/style.css, assets/js/main.js, index.html
Added Newsletter section on the website
-> designed newsletter
=> Added newsletter - issue#82

index.html
Now when clicked on subscribe it form field will show Thank you for subscribing to our newsletters instead of their emails.
Fixes #101 
* Hardware:
* Toolchain:
* SDK:
=> Changed newsletter

.gitignore, assets/css/style.css, dist/index.html, index.html
Improved the timeline design by adding animations to it.
Fixes #84
=> Improving timeline design

team.html
Just changed the href link to /title.html
- manual test
=> Home Link Fixed #108

assets/js/main.js, index.html
Added a regular expression which validates the syntax of a valid email address on click of the `Subscribe Now`.
Fixes #106 
Tested against the following email addresses for valid addresses:
- email@example.com
- firstname.lastname@example.com
- email@subdomain.example.com
- firstname+lastname@example.com
- email@123.123.123.123
- 1234567890@example.com
- email@example-one.com
- email@example.name
Tested against the following email addresses for invalid addresses:
- email
- @example.com
- email @example.com
- email@ example.com
- email@example .com
-  email@example.com
=> Fix: Add email validation to newsletter subscription

event.html, index.html, project.html, team.html
Changed Webinar to Event.
Fixes #106 
Tested against the following email addresses for valid addresses:
- tested
=> Changed webinar to event

index.html
* Hardware:
* Toolchain:
* SDK:
=> Issue #111 solved

index.html
* Hardware:
* Toolchain:
* SDK:
=> Issue Resolved

assets/css/style.css, index.html
Added the toggle button for switching to a dark theme
Fixes #81 
Screenshot for the changes made is attached below-
=> Added toggle button

assets/css/style.css, index.html
Reverts StudentCode-in/StudentCode-in.github.io#123
=> Revert "Added toggle button"

project.html
issue fixed #130 
Fixes # 130
Changes that were made, were static in nature so I just tested it locally
=> Solving issue #130 Nav bar bug

assets/css/style.css
#129
Fixed Screen Overlay on  Header
Changes that were made, were static in nature so I just tested it locally
=> Fixed Screen-Overlay on header

assets/css/style.css
Reverts StudentCode-in/StudentCode-in.github.io#132
=> Revert "Fixed Screen-Overlay on header"

assets/css/style.css, assets/css/style3.css
#129 
As changes are static , so it is tested locally.
=> Fixed Screen Overlay on Screen Header

assets/js/main.js, index.html
Storing the newsletter emails into the firebase DB
collecting email id's - From newsletter #95
- [x ] New feature (non-breaking change which adds functionality)
- [x ] This change requires a documentation update
Manual testing has been done.
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
=> Fixing issue: collecting email id's - From newsletter #95

assets/css/style.css, index.html
Fixes #87 
Added Styling To The Registration Popup Box...
Screenshots of the changes-
Before-
After-
=> Added Styling To The Registration Popup Box
